version: "3"
services:
  backend:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: {{CONTAINER_NAME}}
    ports:
      - "${CONTAINER_PORT}:8080"
    env_file:
      - .env
    restart: always
    networks:
      - shy

networks:
  shy:
    external: true
