services:
  backend:
    image: {{IMAGE}}
    container_name: {{CONTAINER_NAME}}
    ports:
      - "{{PORT}}:8080"
#    env_file:
#      - .env
    restart: always
    networks:
      - shy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
    restart: always
    networks:
      - shy

networks:
  shy:
    external: true