services:
    backend:
      image: subihwang/backend
      container_name: backend
      ports:
        - "8080:8080"
      env_file:
        - .env
      restart: always
      networks:
        - shy
networks:
  shy:
    external: true