services:
  backend:
    image: {{IMAGE}}
    container_name: {{CONTAINER_NAME}}
    ports:
      - "{{PORT}}:8080"
#    env_file:
#      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    networks:
      - shy

networks:
  shy:
    external: true