services:
  backend:
    image: {{IMAGE}}
    container_name: {{CONTAINER_NAME}}
    ports:
      - "{{PORT}}:8080"
    env_file:
      - .env
    restart: always
    networks:
      - shy

networks:
  shy:
    external: true