services:
  backend:
    image: {{IMAGE}}
    container_name: {{CONTAINER_NAME}}
    ports:
      - "{{PORT}}:8080"
#    env_file:
#      - .env
    restart: always
    networks:
      - shy
    volumes: []  # 빈 볼륨 배열 명시적 설정함으로써 볼륨 설정 충돌 방지

networks:
  shy:
    external: true