services:
  frontend:
    image: subihwang/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - shy

networks:
  shy:
    external: true