spring:
  datasource:
    url: ${DB_URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: 8080
