spring:
  datasource:
    url: ${DB_URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_BOOK_GROUP_ID}

server:
  port: 8080
